#!/usr/bin/env python3
"""
CTF Challenge: Operation Firewall Breach
Setup Script — Run this ONCE to initialize the challenge.

NOTE FOR CHALLENGE AUTHORS:
  The flag is NOT stored anywhere in plain text in the distributed files.
  flag.enc contains the AES-256-CBC encrypted ciphertext.
  flag.meta contains the HMAC for integrity verification.
  Neither file can reveal the flag without the correct defense state.
"""

import os
import sys
import json
import time
import base64
import subprocess


# ─── Pre-encrypted flag blob (generated by challenge author, never changes) ───
# Key derived from: all 5 defense vectors correctly blocked + pepper
# This blob is useless without implementing all 5 defense rules correctly.
_FLAG_ENC_B64 = (
    "v7MuCT52z7dwF7HlZ5Wr9NsV0D+hWqWGp1vH4QRNFWpbZxpS62oeNcucG6//"
    "H8jn0higfA04yivEhk1a+8VZ0A=="
)
_FLAG_MAC = "ffaaa3c8e0d481fe0ea19e4ea0605002dae1a1d1441de9fbbf73713699801e43"

_FLAG_META = {
    "version": 1,
    "algorithm": "AES-256-CBC",
    "kdf": "PBKDF2-HMAC-SHA256",
    "iterations": 200000,
    "required_vectors": sorted([
        "sqli", "xss", "path_traversal", "brute_force", "log_injection"
    ]),
    "mac": _FLAG_MAC,
    "hint": "The key is derived from your defense. Block all 5 attack vectors correctly.",
}


def check_deps():
    print("[SETUP] Checking dependencies...")
    try:
        import Crypto
        print("  ✓ pycryptodome")
    except ImportError:
        print("  ✗ pycryptodome missing. Installing...")
        subprocess.run([sys.executable, "-m", "pip", "install", "pycryptodome", "-q"])

    try:
        import requests
        print("  ✓ requests")
    except ImportError:
        print("  ✗ requests missing. Installing...")
        subprocess.run([sys.executable, "-m", "pip", "install", "requests", "-q"])


def setup_dirs():
    print("[SETUP] Creating directories...")
    for d in ["server", "server/public", "attacker", "defender", "flag_system", "docs"]:
        os.makedirs(d, exist_ok=True)

    with open("server/public/readme.txt", "w") as f:
        f.write("Nothing to see here. Keep looking.\n")

    # Empty defense state — participants must earn the flag
    with open("defender/defense_state.json", "w") as f:
        json.dump({"rules": {}, "activated_at": time.time()}, f)

    print("  ✓ Directories ready")


def write_flag_files():
    print("[SETUP] Writing encrypted flag files...")
    os.makedirs("flag_system", exist_ok=True)

    # Write the pre-encrypted ciphertext
    with open("flag_system/flag.enc", "w") as f:
        f.write(_FLAG_ENC_B64)

    # Write metadata (HMAC for integrity, no plaintext flag)
    with open("flag_system/flag.meta", "w") as f:
        json.dump(_FLAG_META, f, indent=2)

    print("  ✓ flag.enc written  (encrypted ciphertext — useless without correct defenses)")
    print("  ✓ flag.meta written (HMAC + metadata — no plaintext flag)")


def verify():
    print("[SETUP] Verifying setup...")
    assert os.path.exists("flag_system/flag.enc"),   "flag.enc missing"
    assert os.path.exists("flag_system/flag.meta"),  "flag.meta missing"
    assert os.path.exists("server/server.py"),        "server.py missing"
    assert os.path.exists("attacker/attacker.py"),    "attacker.py missing"
    assert os.path.exists("defender/defender.py"),    "defender.py missing"

    # Quick sanity: confirm flag.enc is valid base64 and non-trivial length
    with open("flag_system/flag.enc") as f:
        enc = f.read().strip()
    decoded = __import__("base64").b64decode(enc)
    assert len(decoded) >= 32, "flag.enc too short — corruption?"

    print("  ✓ All files present and flag.enc verified")


def print_instructions():
    print("""
╔══════════════════════════════════════════════════════════════════╗
║         SETUP COMPLETE — OPERATION: FIREWALL BREACH             ║
╠══════════════════════════════════════════════════════════════════╣
║  Open 3 terminals and run:                                       ║
║                                                                  ║
║  Terminal 1 (Server):                                            ║
║    python server/server.py                                       ║
║                                                                  ║
║  Terminal 2 (Attacker — auto-starts waves):                      ║
║    python attacker/attacker.py                                   ║
║                                                                  ║
║  Terminal 3 (Your Defender — edit this!):                        ║
║    python defender/defender.py                                   ║
║                                                                  ║
║  When ready to test:                                             ║
║    python defender/defender.py validate                          ║
║    python defender/defender.py flag                              ║
║                                                                  ║
║  Check attack status:                                            ║
║    curl http://localhost:8888/status                             ║
╚══════════════════════════════════════════════════════════════════╝
""")


if __name__ == "__main__":
    print("\n  [CTF] Operation: Firewall Breach — Setup\n")
    check_deps()
    setup_dirs()
    write_flag_files()
    verify()
    print_instructions()